### ISSUE TITLE
Class for integration of ONS, ONE, FOBI

### ISSUE THREAD

**Issue by FrancescoVit** [enpadasi/Ontology-for-Nutritional-Studies#10]
From this issue https://github.com/FoodOntology/joint-food-ontology-wg/issues/20 @cyang0128 @pcastellanoescuder 

Request of addition of a term in ONS

**label**: Nutritional research assay
**superclass** OBI:OBI_0000070 ("Assay") or OBI:OBI_0000066 ("Investigation")
**definition**:  

For the super-class, I would prefer the "assay" rather than the "investigation". Referring to how, for example, ISA-tool define those concepts, I feel more comfortable in relating the "Dietary survey method" and the "Food biomarker analysis" under the "assay" concept, so they can be part of a more complex "investigation". 

For reference

OBI:Assay "A planned process with the objective to produce information about the material entity that is the evaluant, by physically examining it or its proxies."

OBI:Investigation "a planned process that consists of parts: planning, study design execution, documentation and which produce conclusion(s)."

After your feedback on the assay vs investigation placement, I'll try and make a definition, if you do not already have something in mind.

**Comment by cyang0128** [comment]
@FrancescoVit indeed, Assay is more appropriate! I agree :) Besides, I have nothing in my mind regarding its definition, I would appreciate if you could make one! cheers!!!

**Comment by pcastellanoescuder** [comment]
@FrancescoVit absolutely agree with the "assay" term. I also think it's much more appropriate:)

**Comment by FrancescoVit** [comment]
So:

**label:** Nutritional research assay (ONS_XXXXXX)
**superclass:** OBI:OBI_0000070 ("Assay") 
**definition:** Any type of assay that can be performed in the context of a nutritional study

**label:** Food biomarker analysis assay (ONS_YYYYYY)
**superclass:** ONS_XXXXXX 
**definition:** An assay that is aimed at measuring the quantity of known (or unknown) food consumption biomarker in biological fluids (e.g. urine, blood, serum).

Problem I see, the ambiguity between "biomarker" and "metabolite". I hope that @pcastellanoescuder could contribute on this aspect. Thinking out loud, and have not checked if something like this is in FOBI or not, it seems almost unavoidable to also create:

**label:** food consumption biomarker (ONS_ZZZZZ or FOBI)
**superclass:** unsure, some continuant I would say
**definition:**  A chemical analyte measured in a biological fluid (e.g. urine, blood, serum) originated as a result of the consumption and metabolism of a specific food by human.

**Comment by FrancescoVit** [comment]
Update with recent discussion on the JFO tracker

**label:** Nutritional research assay (ONS_XXXXXX)
**superclass:** OBI:OBI_0000070 ("Assay")
**definition:** Any type of assay that can be performed in the context of a nutritional study

**label:** Food biomarker analysis assay (ONS_YYYYYY)
**superclass:** ONS_XXXXXX
**definition:** An assay that is aimed at discovering new potential metabolites as food consumption biomarker, or to measure/validate known food consumption biomarker in biological fluids (e.g. urine, blood, serum).

**label:** Food biomarker validation assay (ONS_ZZZZZZ)
**superclass:** ONS_YYYYYY
**definition:** An assay that is aimed at measuring the quantity (or presence) of food intake biomarkers in a biological sample (e.g. urine, blood, serum, feces) in order to evaluate the consumption of defined foods

**label:** Food biomarker discovery assay (ONS_WWWWWW)
**superclass:** ONS_YYYYYY
**definition:** An assay that is aimed at measuring the quantity (or presence) of food related metabolites in a biological sample (e.g. urine, blood, serum, feces) in order to identify/discover new food intake biomarkers

**Comment by FrancescoVit** [comment]
Update to the last discussed version for definitions

**label:** Nutritional research assay (ONS_0000110)
**superclass:** OBI:OBI_0000070 ("Assay")
**definition:** Any type of assay that can be performed in the context of a nutritional study

**label:** Food biomarker analysis assay (ONS_0000111)
**superclass:** ONS_0000110
**definition:** An assay that is aimed at discovering new potential metabolites as food consumption biomarkers, or to measure/validate known food consumption biomarkers in a biological sample (e.g. urine, blood, serum, feces).

**label:** Food biomarker validation assay (ONS_0000112)
**superclass:** ONS_0000111
**definition:** An assay that is aimed at measuring the quantity (or presence) of food intake biomarkers in a biological sample (e.g. urine, blood, serum, feces) in order to evaluate the consumption of defined foods

**label:** Food biomarker discovery assay (ONS_0000113)
**superclass:** ONS_0000111
**definition:** An assay that is aimed at measuring the quantity (or presence) of food related metabolites in a biological sample (e.g. urine, blood, serum, feces) in order to identify/discover new food intake biomarkers
