### ISSUE TITLE
Derives from must not (!) be reflexive

### ISSUE THREAD

**Issue by matentzn** [enpadasi/Ontology-for-Nutritional-Studies#12]
![image](https://user-images.githubusercontent.com/7070631/111450854-b6207280-8708-11eb-8afb-4eeaf9392de7.png)

You should never redefine the semantics of RO properties in your ontologies! We are trying to re-use ONS, but this "Reflexive" property causes all ontologies using ONS (with BFO) to be inconsistent.. Please remove the reflexivity!

**Comment by matentzn** [comment]
Awesome, thank you for the prompt fix :)

**Comment by FrancescoVit** [comment]
Sorry for the inconvenience, I am trying to fix all of those bugs in the next release. Please, consider that those changes are not in the ONS version that is referred by ontobee or OLS, but rather in this file https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/ons.owl which will be (hopefully very soon) tracked by ontobee.

Sorry for this, but I would like to also solve the double labels bug before committing to the ontobee track.

I will also check for other problems with original RO properties in root ONS file.

**Comment by matentzn** [comment]
Sounds great :)
