### ISSUE TITLE
ONS does not parse

### ISSUE THREAD

**Issue by cmungall** [enpadasi/Ontology-for-Nutritional-Studies#14]
I can't reopen #8 so opening a new ticket

```
2021-05-12 18:15:28,430 ERROR (CommandRunner:4815) could not parse:http://purl.obolibrary.org/obo/ons.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontodog/obi_in_ons.owl> Cause: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontodog/obi_in_ons.owl
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)
```

**Comment by matentzn** [comment]
Yes, has been happening again for a while on dashboard as well: http://dashboard.obofoundry.org/dashboard/index.html

So not temporary. Please merge imports or at least use PURLs.

**Comment by FrancescoVit** [comment]
This is from the OBO tracker right? If yes, it still points to an old version of ONS with muttiple imports. Right now, in the ons.owl in master folder this should be fixed and should work. I still have a OBO format problem with multiple annotation, as in ONS some classes (with annotation) are duplicated in the master owl file and in the owl file of the imports. In ths way, annotations are getting doubled.

At any rate, I could easily fix this by finalizing the release, and pointing to the latest version in ons.yml. There would still be a formal error for those annotations however, that could be fixed later on

**Comment by FrancescoVit** [comment]
Just made the release using the GitHub release system. Updated the yaml file to point to /master/ons.owl

Hope this fix the issues

**Comment by FrancescoVit** [comment]
@matentzn @cmungall sorry for using this issue instead of opening another one. I noticed that ONTOBEE is pointing to an old version of ONS. The "IRI" and "Download" entry in the ONS correctly point to the latest version, but term research and browsing of terms in ONTOBEE is not... (I am not finding recently added terms)

Could you help me with that?

**Comment by matentzn** [comment]
See here: https://github.com/EBISPOT/OLS/issues/485

If this persists, you can ping @yongqunh via email or slack

**Comment by FrancescoVit** [comment]
Thank you for the suggestion. Problem fixed

**Comment by yongqunh** [comment]
That's great. Glad to help.

**Comment by FrancescoVit** [comment]
@yongqunh sorry to bring this back, but I continue on having Ontobee record for ONS that fails to update to the latest ons.owl release. Ontobee points to v 1.2.0, while the repository is at 1.2.2

Can't undertand why this is happening, may I have done some wrong set-up at initial commit in the obo-foundry?

**Comment by matentzn** [comment]
FYI there are some migration processes happening at Ontobee that disrupt autoupdates for a few weeks - if you want this dealt with, best email @yongqunh directly :)

**Comment by yongqunh** [comment]
The updating should be done now: http://www.ontobee.org/ontology/ONS . Hopefully the ontobee automatic updating will be done soon. Meanwhile, please feel free to contact. Thanks.

**Comment by FrancescoVit** [comment]
closing as solved
