### ISSUE TITLE
NTRs for Dietary Reference Intake terms

### ISSUE THREAD

**Issue by ddooley** [enpadasi/Ontology-for-Nutritional-Studies#16]
This Is a request for a handful of standard Dietary Reference Intake terms, held in this Google Sheet ready for comment.
https://docs.google.com/spreadsheets/d/1-_O51W78nPFCkvfBRufz-XEberdfldOTCbPMkEsUv4kg
Francesco you have edit permission on it. A preview of the terms is below:

parent class | label | definition | definition source
-- | -- | -- | --
data item | dietary reference intake | A data item which is a quantitative estimate of nutrient intake to be used as a reference value for planning and assessing diets for healthy people. | &nbsp;
dietary reference intake | average daily nutrient intake level | A dietary reference intake which is an average of daily nutrient intake values to be used as a reference for planning and assessing diets for healthy people. | https://www.nap.edu/download/10490
average daily nutrient intake level | recommended dietary allowance | An average daily nutrient intake level which is sufficient to meet the nutrient requirement of nearly all (97 to 98 percent) healthy individuals in a group. | https://www.nap.edu/download/10490
average daily nutrient intake level | adequate intake | An average daily nutrient intake level which is recommended based on observed or experimentally determined approximations or estimates of nutrient intake by a group (or groups) of apparently healthy people that are assumed to be adequate with respect to deficiency or disease criteria. | https://www.nap.edu/download/10490
average daily nutrient intake level | tolerable upper intake level | An average daily nutrient intake level which is the highest level that is likely to pose no risk of adverse health effects to almost all individuals in the general population. | https://www.nap.edu/download/10490
average daily nutrient intake level | estimated average requirement | An average daily nutrient intake level which is estimated to meet the requirement of half the healthy individuals in a particular life stage and gender group. | https://www.nap.edu/download/10490
average daily nutrient intake level | Estimated Energy Requirement | An average daily nutrient intake level which is predicted to maintain energy balance in healthy, normal weight individuals of a defined age, gender, weight, height, and level of physical activity consistent with good health. | https://www.nap.edu/download/10490
dietary reference intake | Acceptable Macronutrient Distribution Range | A dietary reference intake data item which is a range of intake for a particular energy source (protein, fat, or carbohydrate), expressed as a percentage of total energy (kcal), that is associated with reduced risk of chronic disease while providing adequate intakes of essential nutrients. | https://www.nap.edu/download/10490

I've linked this in for comment from the JFOW group.

**Comment by FrancescoVit** [comment]
@ddooley proposed classes were created in the pre-release version ([ons-edit.owl](https://github.com/enpadasi/Ontology-for-Nutritional-Studies/blob/master/src/ontology/ons_edit.owl))
Just a note, the URL for definition source point to a page not accessible to anyone, asking for a login to "MYNAP"
I was not able to open the spreadsheet (file does not exist) to check for other desired annotations or axioms. If any addition to the classes has to be done, let me know. 

Keeping this open for further discussion, if there is nothing to add I'll close

**Comment by ddooley** [comment]
Hi,
Ah, somehow an extra "g" got added on to the sheet URL, my bad.  The link should be: https://docs.google.com/spreadsheets/d/1-_O51W78nPFCkvfBRufz-XEberdfldOTCbPMkEsUv4k/edit .  There were just a few other rdfs:comments that could be added from there.

And here is a better URL for the document reference:
https://www.nap.edu/catalog/10490/dietary-reference-intakes-for-energy-carbohydrate-fiber-fat-fatty-acids-cholesterol-protein-and-amino-acids
That is publcily accessable without login, and the pdf is free to download.

**Comment by ddooley** [comment]
Thanks!

**Comment by ddooley** [comment]
p.s. there are abbreviations and one example of usage that should be included too.

**Comment by ddooley** [comment]
Something I see in your ons-edit.owl file - it seems like you have merged the import files directly into it.  Have you considered leaving the import files as separate files, which are linked in ons-edit.owl rather than merged in it?  Then ons-edit.owl primarily holds ons terms and little else.

**Comment by FrancescoVit** [comment]
Actually imports are not merged in the main file, rather they are automatically imported when opening ons.owl (or ons-edit.owl) as they are declared as imports in  

`<owl:imports rdf:resource="https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ONS_imports.owl"/>`

In Protègè, in fact, you can remove the imports and loose annotations. Isn't that the expected behavior?

**Comment by FrancescoVit** [comment]
> https://www.nap.edu/catalog/10490/dietary-reference-intakes-for-energy-carbohydrate-fiber-fat-fatty-acids-cholesterol-protein-and-amino-acids
> That is publcily accessable without login, and the pdf is free to download.

Yes, just saw the "download as guest" simply asking for a mail.
Updating!

**Comment by ddooley** [comment]
You should check ons-edit.owl because full FOODON terms do appear to be in that file.  Same with ons.owl  - that is why they are each above 4.2Mb.  I see ons-edit.owl does have an imports/ontofox_import.owl file, but if you disconnect it I think you will still find lots of FOODON_12345678 terms fully defined in the main file.

**Comment by ddooley** [comment]
p.s. I just learned how to remove them automatically with a ROBOT command that takes out from the main file everything that is present in an import file, so can help with that part.

**Comment by FrancescoVit** [comment]
Yes, some terms are for sure fully defined in main ons.owl

> p.s. I just learned how to remove them automatically with a ROBOT command that takes out from the main file everything that is present in an import file, so can help with that part.

that was what I exactly searched for! You mean taking out entire class, or their annotations? that would be useful to also remove double annotation problem #15

**Comment by ddooley** [comment]
This should work:

robot convert --input imports/ontofox_import.owl --format ofn --output temp-import.ofn
grep -v '^Declaration' source-import.ofn > temp.ofn
robot unmerge --input ons_edit.owl --input temp.ofn --output ons-edit-2.owl

Check ons_edit_2.owl to see if that's ok (all classes which are described in import file are now removed from ons_edit_2.owl), and if so, rename it back to ons_edit.owl
You can do the same for foodon_import.owl if you want if its content is different from what is in ontofox_import.owl .  You can see how I got Nico's help to figure that out at bottom of this thread: https://github.com/ontodev/robot/issues/848

**Comment by FrancescoVit** [comment]
Cited the above comment on issue #15 which is dedicated to the problem of multiple annotations. 

The requested terms are now in `/src/ontology/ons-edit.owl` they will be in `/master/ons.owl` at next release (in few days I suppose)
