### ISSUE TITLE
Define and add class "food choices"

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#21]
Add a class:

**label** food choices [ONS:0000132]
**superclass** information content entity
**definition** The selection of specific foods from a variety of available options

Rationale: this class would be the result of the "food management process", which in turn is a consequence of the "determinant of diet" class. It would describe the food decisions made by the organism as a result of all the environmental conditioning around it. It would directly denote the "dietary pattern" [ONS_0000094].

**Comment by FrancescoVit** [comment]
Integration and minor corrections

**label** food choice [ONS:0000132]
**superclass** information content entity
**definition** food choice refers to any decision an organism makes regarding food and diet. It both refers to the selection of specific foods to be consumed by an organism, from a variety of available options, and to the choices regarding quantity and mode of consumption of foods. Food choice are direct consequence of the food management process, and depends on a variety of determinants of diet
**has synonym** food selection
**rdfs:seeAlso** 
https://www.sciencedirect.com/topics/food-science/food-choice; https://www.eufic.org/en/food-safety/category/food-choice
