### ISSUE TITLE
Define and add class "food choice management process"

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#22]
Add a class:

**label** food choice management process [ONS:0000128]
**superclass** information content entity
**definition** the process by which an individual makes choices about food consumption, based on multiple determinants

Rationale: individuals make their "food choices" [ONS:0000132] as a result of a decision-making process that we are defining as the "food choice management process". In this way, each individual "dietary pattern" [ONS:0000094] becomes the result of the "food choice management process" that includes a balance of healthy and unhealthy "food choices" which are influenced by the "determinant of diet" class

**Comment by FrancescoVit** [comment]
Integration and minor corrections

**label** food choice management process [ONS:0000128]
**superclass** process
**definition** the food choice management process refers to the complex decision-making process an organism carry out to realize choices about which food to be consumed, and to the choices regarding quantity and mode of consumption of foods.

**Comment by AnaReisCosta** [comment]
I would change "realize" to "make" because realizing in English is taking the notion of something or recognizing, instead of doing something. I also think that it should be "an organism carries out" instead of "carry"
