### ISSUE TITLE
Define and add class "dis- food choice management process "

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#23]
Add a class:

**label** dis- food choice management process [ONS:0000130]
**superclass** information content entity
**definition** a food choice management process resulting in unhealthy food choices

Rationale: the "food choice management process" [ONS:0000128] entails healthy and unhealthy food choices. To the process associated with unhealthy food choices, we are attributing the class "dis- food choice management process" because it has its own associated motivations. Moreover, we believe the unhealthy "food choices" shouldn't be demonized, because they do not characterize the dietary pattern alone. It is the balance/ratio between the "dis- food choice management process" and the other proposed class "eu - food management process" that will characterize the dietary pattern as healthy or not.

**Comment by FrancescoVit** [comment]
**label** mismanagement of food choice [ONS:0000130]
**superclass** food choice management process [ONS:0000128]
**definition** a food choice management process resulting in unhealthy food choice
**example of usage** Wine consumption is part of the Mediterranean diet, which can be regarded as a healthy dietary pattern. A mismanagement of red wine, which might be related to alcohol addiction, leads to unhealthy food choice about the number of red wine servings consumed per day (> 2). This produces a specific dietary pattern and diet, with unfavourable health consequences, even though all the other requirements to adhere to a Mediterranean diet are met
**curator note**
