### ISSUE TITLE
Define and add class "eu- food choice management process"

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#24]
Add a class:

**label** eu- food choice management process [ONS:0000129]
**superclass** information content entity
**definition** a food choice management process resulting in healthy food choices

Rationale: the "food choice management process" [ONS:0000128] entails healthy and unhealthy food choices. To the process associated with healthy food choices, we are attributing the class "eu- food choice management process" because it has its own associated motivations. Moreover, we believe the healthy "food choices" are not enough to qualify a dietary pattern as healthy, since the dietary pattern fitness is the consequence of the balance/ratio between the "eu- food choice management process" and the other proposed class "dis- food management process". This balance will define the dietary pattern as healthy or not.

**Comment by FrancescoVit** [comment]
**label** healthy management of food choice [ONS:0000129]
**superclass** food choice management process [ONS:0000128]
**definition** a food choice management process resulting in healthy food choice
**example of usage** wine consumption is part of the Mediterranean diet; as opposed to the "mismanagement of food choice" an healthy management food choice of red wine consumption in the context of mediterranean diet dietary pattern, would be that of limit consumption to a maximum of 2 glasses per day during meals (https://www.health.harvard.edu/blog/a-practical-guide-to-the-mediterranean-diet-2019032116194)
**curator note**
