### ISSUE TITLE
Define and add class "Rural diet"

### ISSUE THREAD

**Issue by AnaReisCosta** [enpadasi/Ontology-for-Nutritional-Studies#27]
Add a class:

**label** Rural diet [ONS:0000134]
**superclass** information content entity
**definition** Dietary pattern characteristic of the lifestyle in isolated/rural areas, commonly in developing countries. It is mainly composed of naturally available food products, including fresh animal protein and vegetables while excluding industrially processed foods. Nevertheless, it is common to use traditional food processing methods to improve nutrient availability, digestibility or to increase conservation time to avoid scarcity. These methods include soaking, fermentation, cooking, pounding, and sprouting.

**Rationale:** As the term "Western diet" became more popular, several opposing terms have been employed to define the dietary patterns of countries that do not follow the industrialized countries lifestyle. With this in mind, we propose the introduction of the term "rural diet" to define the dietary pattern that was conserved in rural areas that did not go through massive behaviour changes due to the industrial revolution.

**Comment by ddooley** [comment]
I'd advocate allowing the label to be longer, and adding synonyms as needed, if that enables a closer characterization of the diet in question.  So "local agrarian diet" possibly, or something like that.

**Comment by FrancescoVit** [comment]
**label** rural diet [ONS:1000066]
**superclass** diet by nutritional composition [ONS:1000005]
**definition** the diet characteristic of the lifestyle in isolated/rural areas, commonly in developing countries. It is mainly composed of naturally available food products, including fresh animal protein and vegetables while excluding industrially processed foods. Nevertheless, it is common to use traditional food processing methods to improve nutrient availability, digestibility or to increase conservation time to avoid scarcity. These methods include soaking, fermentation, cooking, pounding, and sprouting.
**has exact synonym" traditional diet; local agrarian diet

**Comment by FrancescoVit** [comment]
Add a class:

**label** rural diet dietary pattern [ONS:2000045]
**superclass** dietary pattern  by nutritional composition [ONS:2000005]
**definition** a dietary pattern that define the quantity, variety or combination of different food in a rural diet
