### ISSUE TITLE
ONS use of "is quality measurement of"

### ISSUE THREAD

**Issue by ddooley** [enpadasi/Ontology-for-Nutritional-Studies#35]
As brought up in bottom of https://github.com/FoodOntology/foodon/issues/206 this relation can't connect to processes on the right side. It can only connect to qualities there.

Can you remove the bottom two axioms shown here asap?!

<img width="813" alt="image" src="https://user-images.githubusercontent.com/4000582/173196503-fdc10393-c93a-448a-96ce-0496d57ffc9d.png">

There is a different new relation available for connecting processes to the qualities they regulate, as shown in this diagram:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/4000582/173196579-25d1d747-e9b4-4bf4-b5cc-a0dc9ece5cfc.png">

But maybe you just want to say instance "water activity of parmigiano regiano" (a measurement datum) is about "parmigiano regiano shaping and salting"? If we're talking about a measure that can be taken repeatedly during the cheese shaping and salting process? Or maybe "water activity of parmigiano regiano"  is a "water concentration datum" and is about "parmigiano regiano".

**Comment by FrancescoVit** [comment]
Removed now.
Intent was referred to final product values, so no measure in time but rather values that should be respected by regulations. The "water activity in parmigiano reggiano" has a specific numeric value, and represent the quality measure resulting from the process of "shaping and salting". Seems that a class in between (a material entity) is missing, which would be the actual aspect changing as result of the process, which would take the quality measurement.
