### ISSUE TITLE
ONS has instances for BFO terms as well as classes

### ISSUE THREAD

**Issue by ddooley** [enpadasi/Ontology-for-Nutritional-Studies#37]
This is causing an issue as I import ONS terms from the root entity branch via OntoFox, which is including the instance.  Could this be fixed soon?  BFO terms shouldn't have instances.  I know how this can arise accidentally when opening say an ons-edit.owl file but the BFO import file is missing, and pressing save - Protege creates instances by default in certain circumstances as I recall.

**Comment by FrancescoVit** [comment]
Problem seems to be in the [import file](https://github.com/enpadasi/Ontology-for-Nutritional-Studies/blob/master/src/ontology/imports/ONS_import_01192022_noDeprec.owl). Looking for what raised the problem as I can't seem to really find individuals declaration for BFO tems

**Comment by ddooley** [comment]
This will be resolved in next ONS release, shortly!
