### ISSUE TITLE
Add class for "Food management process"

### ISSUE THREAD

**Issue by FrancescoVit** [enpadasi/Ontology-for-Nutritional-Studies#6]
Add Class as discussed in IFOW (FoodOntology/joint-food-ontology-wg#8).

A super-class intended to have all possible processes that guide the choices of an organism when dealing with food and nutrition. Could be a very broad category, encompassing socio-economical processes, personal tastes, and similar in a complex process of choice that utimately influence the dietary pattern (and as a consequence, the diet).

This process, could depend on another class to be created called "determinants of diet".

**label** Food management process
**superclass** BFO:0000015 (process) 
**definition:** The process an organism has which achieves a dietary pattern and involves food availability, physiological or psychological motivation, selection, episodic consumption, and digestion.

Some axiom idea:
"food management process" has output "dietary pattern"
"food management process" is related to "determinants of diet"

**Comment by ddooley** [comment]
I think this one can be closed now? I see "organism food management process" in ONS now.

**Comment by FrancescoVit** [comment]
Right!
