### ISSUE TITLE
Create OBO file from ONS

### ISSUE THREAD

**Issue by matentzn** [enpadasi/Ontology-for-Nutritional-Studies#9]
Moved from:

ONS owl violates the OBO profile (multiple labels/comments etc):

```
OBO STRUCTURE ERROR Ontology does not conform to OBO structure rules:
multiple name tags not allowed. in frame:Frame(ONS:0000101 id( ONS:0000101)comment( Should break the definition down into separate terms, e.g. bioaccessable should be defined separately.)property_value( IAO:0000117 ENPADASI_WP4 xsd:string)name( food digestion)name( Food digestion)def( Digestion is the breakdown of large food molecules into small water-soluble food molecules. The breakdown is both mechanical and chemical (enzymatic digestion). During digestion, food components are released from the food matrix and may become bioaccessible.)def( Digestion is the breakdown of large insoluble food molecules into small water-soluble food molecules. The breakdown is both mechanical and chemical (enzymatic digestion). During digestion, food components are released from the food matrix and become bioaccessible. Bioaccessible molecules can be absorbed.)is_a( GO:0008150))
```

@FrancescoVit you can use

```
 robot convert -I https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/ons_release_v1.2.owl -f obo --check false -o ons_release_v1.2.obo
```

to circumvent the issue (--check false). This produces slightly dodgy OBO, but we all do it, all the time.

This particular error, by the way, should be fixed: you should never use multiple labels on a class. Use 

```
 robot report -I https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/ons_release_v1.2.owl -o report.txt
```

To identify such issues!

**Comment by ddooley** [comment]
I think related to this is that ONS needs a root ons.owl file.  Francesco, we could have a short call to finalize that. At moment OntoBee and OLS have old content for this ontology as a result of the current way of handling versions.

**Comment by FrancescoVit** [comment]
I am going over the multiple_definition and multiple_label ONS classes, and noted that in some cases the error raises from having specified a language tag, see example attached

![immagine](https://user-images.githubusercontent.com/8997412/111647043-6faf3e80-8802-11eb-81ef-a7f016389caa.png)

Here we have two textual definition as one is "general" and implicitly in English language (defaultLanguage in ontology header section), while in an additional definition we specified the @en language tag. The same for the labels.

In this case I could easily remove the non langage tagged definition or label, but how to formally deal with it if I am to include other languages labels as well? All in all, I sort of think that this should not be a formal error

**Comment by ddooley** [comment]
Indeed, take out the labels and definitions that don't have a language tag.
Now, as I recall some OBO validation tool may not accept multiple definitions that DO have other language tags besides english.  As a workaround until they do (they should at some point to get multilingual IMHO!) one could separate out the other language content into a separate import file, and just keep that disconnected and added by users when they want that multilingual capability for their applications.

**Comment by FrancescoVit** [comment]
Language tag removed, this specific issue is solved. Closing and referring to #15 for the new issue on general duplicated annotations
